### ISSUE TITLE
Criação do Release notes

### ISSUE THREAD

**Issue by show-dawn** [unb-mds/2023-2-Squad04#118]
**Descrição**

Nessa issue iremos criar o release notes do projeto

**Tarefas** 
 - [x] Analisar as Sprints
 - [x] Subir para o Github

**Comment by Julio1099** [comment]
# Release Notes - Versão 2.0.0

### Data de Lançamento: 12 de dezembro de 2023

Estamos animados em apresentar a versão 2.0.0 do nosso software, que traz uma série de melhorias significativas, novos recursos e atualizações na documentação para aprimorar a usabilidade e a funcionalidade geral. Confira abaixo os principais destaques desta versão:

 ### Novos Recursos e Atualizações de Documentação:

## Implementação do Docsify:

Introduzimos o Docsify para a documentação, proporcionando uma experiência mais interativa e fácil de navegar. Agora, você pode explorar nossos recursos e funcionalidades de maneira mais eficiente.

## Atualizações na Documentação:

Realizamos aprimoramentos e atualizações na documentação existente para garantir informações precisas e detalhadas sobre o uso do software.

## Adição do Manual de Design:

Incluímos um manual de design abrangente para orientar os usuários na criação de interfaces intuitivas e eficientes utilizando nossa arquitetura de software.

## Adição do Roadmap:

Apresentamos um roadmap detalhado, oferecendo uma visão clara das futuras atualizações e desenvolvimentos planejados para o software.

# Melhorias na Estrutura do Site:

## Implementação da Base Estrutural do Site:

Reforçamos a estrutura do site para garantir uma navegação mais intuitiva e uma experiência de usuário mais coesa.
Atualizações nos Scripts e Workflows:

## Atualizações no Script de Downloads do Danilo:

Corrigimos e otimizamos o script de downloads, garantindo uma execução mais eficiente e confiável.

## Implementação de Scripts para Manipulação de PDFs:

Introduzimos scripts para listagem, exclusão e leitura de PDFs, junto com workflows agendados para uma execução automática consistente.

## Atualizações no Script de Contagem:

Realizamos correções e melhorias no script de contagem desenvolvido por Fernando e Júlio, acompanhado por workflows agendados para automação.

## Downloads dos PDFs de 2023:

Disponibilizamos uma funcionalidade para efetuar o download dos Diários Oficiais do ano de 2023 diretamente pelo software.

# Introdução do Apexcharts e Script JavaScript:

## Implementação do Apexcharts (Gráficos):

Agora, você pode visualizar dados de forma mais eficaz com a adição do Apexcharts para criar gráficos interativos.

## Script JavaScript para Plotagem de Dados:

Introduzimos um script JavaScript para extrair e plotar os dados gerados pelo script de contagem.

# Arquitetura do Software:

## Desenvolvimento da Arquitetura do Software:

Planejamos e desenvolvemos a arquitetura que sustenta o software, proporcionando uma base robusta para futuras expansões.
