### ISSUE TITLE
Implementar Testes com Pytest

### ISSUE THREAD

**Issue by Carlos-kadu** [unb-mds/2023-2-Squad04#137]
## Descrição
Atualmente, nosso projeto não possui testes automatizados para garantir a qualidade e integridade do código. Este problema tem como objetivo implementar testes utilizando a biblioteca pytest.

## Tarefas
- [x] Configurar o ambiente de teste utilizando o pytest.
- [x] Escrever testes de unidade para funções e métodos críticos do script de download dos pdfs.
- [x] Fazer teste para o readpdf.py utilizando o pytest.

**Comment by Carlos-kadu** [comment]
Teste disponível na branch "testes"!
https://github.com/unb-mds/2023-2-Squad04/tree/testes
![image](https://github.com/unb-mds/2023-2-Squad04/assets/133259317/c93057a9-50d8-40f9-97d6-123a8c35dca0)

**Comment by rayenealmeida** [comment]
![image](https://github.com/unb-mds/2023-2-Squad04/assets/85962730/c32c3afc-8b36-466a-bfb4-5958a203f9c1)
