### ISSUE TITLE
Estudo sobre Praticas DevOps

### ISSUE THREAD

**Issue by patyhelenaa** [unb-mds/2023-2-Squad04#16]
# Estudo sobre Praticas DevOps
## Descrição
Estudar sobre conceito DevOps, Deploy, arquitetura de software e documentação de Software.
## CheckList 

 - [x] Conceito DevOps
 - [x] Arquitetura de Software
 - [x] Documentação de Software
 - [x] Práticas DevOps

**Comment by patyhelenaa** [comment]
# CONCEITO DEVOPS E DEPLOY

## DevOps
-  Devops nada mais é do que a junção de desenvolvimentos e operações, a ideia é unir os desenvolvedores de software com a equipe de operações de TI, promovendo a colaboração entre as partes por meio de automações e comunicação, assim, visando o aceleramento do desenvolvimento de software e melhorando a qualidade daquele projeto.  O time de operações trabalha mais perto dos desenvolvedores assim podendo entender melhor as necessidades do sistema e ajudar a entendê-las desde o início.

## Deploy
- Processo de lançamento de uma versão de um aplicativo ou serviço em algum ambiente de produção, onde os usuários finais poderão acessá-lo. O Deploy pode ser manual, parcialmente automatizado ou completamente automatizado. Utilizando o Deploy totalmente automatizado está diretamente ligado com o conceito de integração continua.` A maneira de fazer essa integração vai depender diretamente do tipo de projeto desenvolvido`, se for um aplicativo por exemplo, a versão desejada seria colocada nas lojas de apps como Apple para o usuário final poder acessa-la.

 **Aqui esta um vídeo util sobre conceito de Deploy:** 
- https://www.youtube.com/watch?v=gJw7l2JKpuQ

**Comment by patyhelenaa** [comment]
# ARQUITETURA DE SOFTWARE E SUA DOCUMENTAÇÃO
# Arquitetura de Software
-  **DEFINIÇÃO:** A arquitetura de software é um plano abstrato que orienta o desenvolvimento de um sistema de software, garantindo que ele seja organizado, eficiente, atenda aos requisitos e seja flexível o suficiente para futuras mudanças. Ela desempenha um papel fundamental na criação de sistemas de software robustos e sustentáveis.

-  **OBJETIVO:** Gerar métodos eficazes para elaborar, sustentar, modernizar, implantar ( Deploy) e tornar operacional o software.
### `PADROES ARQUITETURAS DE SOFTWARE:`
- `Model-view-controller (MVC)`
O padrão MVC (Modelo, Visão e Controle) separa o projeto do software em três camadas independentes: o modelo (manipulação da lógica de dados), a visão (a interface do usuário) e o controlador (fluxo de aplicação). Esta separação facilita a manutenção do código, que pode ser reutilizado em outros projetos, proporcionando um modelo interativo para o sistema.

- `Layers (camadas)`
Os módulos e componentes do software são organizados em camadas de funcionalidades, que podem ser desconstruídas em diferentes serviços. Este padrão é mais usado em programas de e-commerce.

### Esses são só alguns exemplos de arquiteturas de software, abaixo tem uma publicação muito legal que cita mais alguns exemplos e mais alguns links úteis sobre o assunto:
- https://posdigital.pucpr.br/blog/tipos-de-arquitetura-de-software
- https://www.youtube.com/watch?v=kYx1QC1XZSo
- https://www.youtube.com/watch?v=jUH5lKfpWE0

# Documentação de Software
## Por que Documentar um Software?
- Quando se fala sobre documentação de software entramos em um assunto bem amplo, pois é comum cada um fazer do seu jeito, porém, quando falamos de um projeto em grupo a padronização e mais que bem-vinda aqui. `A documentação desvincula a dependência de processos do sistema em pessoas especificas`, já que todo o andar do projeto não vai estar apenas na cabeça de uma pessoa e sim documentado para todos os integrantes, isso é essencial para o progresso do projeto.
## Como documentar um software?
-Hoje existem várias maneiras de realizar isso, um exemplo é usando a forma UML (Unified Modeling Language) por meio de diagramas. Mas para escolher o melhor método de documentação para seu projeto basta escolher o formato mais útil e ágil para o seu projeto.

**Link útil sobre Documentação ligada a um ambiente ágil:**
- https://www.youtube.com/watch?v=S3NLU898_Cc&t=80s

`**Link útil sobre um exemplo de Documentação C4:**`
- https://www.youtube.com/watch?v=nJzGhjLJ63E

**Comment by aqela-batata-alt** [comment]
# Práticas DevOps
## Roadmap:
O Roadmap de Produto representa um documento estratégico que integra os objetivos do negócio, as demandas dos clientes e as ações necessárias para alcançar esses objetivos. Ele desempenha um papel crucial no planejamento e na comunicação da visão futura do produto para todas as partes interessadas.

Seu principal propósito é harmonizar diferentes perspectivas, organizando as ideias de desenvolvimento do produto, estabelecendo prioridades e buscando a máxima geração de valor para o seu negócio. O Roadmap de Produto é instrumental na resposta a perguntas essenciais sobre a evolução do produto, como "onde estamos atualmente?", "para onde queremos ir?" e "como chegaremos lá?", além de abordar outros aspectos importantes.

## Story Map:
O Story Mapping é uma ferramenta que organiza as histórias de usuário em um modelo que facilita a compreensão das funcionalidades do sistema. Ele auxilia na identificação de lacunas no backlog e no planejamento de lançamentos abrangentes que agregam valor tanto aos usuários quanto ao negócio a cada versão.

Trata-se da visão geral utilizada por equipes ágeis para visualizar roteiros de produtos de alto nível e planos de lançamentos. Ele divide o trabalho em três componentes essenciais:

> Backbone (atividades do usuário): Representa os principais temas ou ações que os usuários podem realizar por meio do fluxo de trabalho.
> 
> Walking skeleton (tarefas do usuário): São as tarefas necessárias para dar suporte ao backbone, garantindo que as atividades do usuário possam ser realizadas de maneira eficaz.
> 
> Histórias de usuário: Essas são subdivisões das tarefas que detalham as ações específicas necessárias para concluir as tarefas.

O Story Mapping é uma ferramenta valiosa para planejar e comunicar de forma eficaz o desenvolvimento do produto, garantindo que as necessidades dos usuários sejam atendidas de maneira sistemática e que o valor seja entregue incrementalmente.

## Protótipo:
A finalidade de um protótipo reside em satisfazer a exigência de aprimoramento, o que, por sua vez, aumentará as probabilidades de sucesso tanto no momento do lançamento quanto após o mesmo. No entanto, é essencial compreender que, quando nos referimos a um protótipo, não estamos tratando de um produto em si, mas sim de uma das ferramentas fundamentais para refinamento e aperfeiçoamento.

O protótipo é essencial para aproximar o desenvolvimento ao usuário, assim diminuindo a lacuna entre o que foi pedido, o que o usuário quer e o que está sendo desenvolvido, assim agilizando o processo produtivo e diminuindo os gastos.


**algumas referências:**
https://leonardo-matsumota.com/2019/03/14/o-mapa-de-historias-story-mapping-e-roadmap-de-produto/
https://azure.microsoft.com/pt-br/resources/cloud-computing-dictionary/what-is-devops
https://www.redhat.com/pt-br/topics/devops
https://www.ibm.com/br-pt/topics/devops
