### ISSUE TITLE
Estudar o que é um parser

### ISSUE THREAD

**Issue by RochaCarla** [unb-mds/2023-2-Squad04#2]
# Descrição

Estudar como funciona o parser, qual o seu objetivo e implementar um parser simples.

# Tarefas

- [ ] Procurar referencias de tutorial parser
- [ ] Olhar um código parser querido diário
- [ ] Implementar um exemplo de um tutorial
- [ ] Documentar

# Critérios de aceitação 

- [ ] Commitei meu código
- [ ] Commitei minha documentacao
- [ ] Apresentação pro grupo

**Comment by RochaCarla** [comment]
olha que lugar mara pra esturdar parser!! link

**Comment by RochaCarla** [comment]
um parser simples do querido diare=io eh esse aqui: link

**Comment by RochaCarla** [comment]
Implementando o exemplo x

**Comment by Julio1099** [comment]
Um parser é um componente de software utilizado para analisar a estrutura de um dado texto ou código fonte. Os parsers são comumente usados em linguagens de programação, compiladores, interpretadores, processamento de linguagem natural (NLP) e em várias outras áreas da computação.

A principal função de um parser é transformar um texto em uma representação estruturada que possa ser facilmente manipulada ou interpretada por um programa. Existem dois tipos principais de parsers:

**Parser de Sintaxe (ou Analisador Sintático)**: Este tipo de parser analisa a estrutura gramatical de um texto para determinar se ele segue as regras da linguagem. Se o texto estiver correto de acordo com a gramática, o parser cria uma árvore de sintaxe ou outra estrutura de dados que representa a estrutura do texto. Caso contrário, ele relata um erro de sintaxe.

**Parser de Linguagem de Marcação**: Este tipo de parser é usado para analisar linguagens de marcação, como HTML, XML e JSON. Ele identifica os elementos e suas hierarquias no documento, tornando mais fácil a extração de informações ou a manipulação do conteúdo.

Resumindo, um parser desempenha um papel importante na interpretação e manipulação de texto estruturado, tornando-o acessível para processamento por programas de computador. Ele é essencial em muitos domínios da computação e da ciência da computação, desde a análise de código fonte até a análise de documentos e comunicação em redes.

**Referências**:
1:https://www.techtarget.com/searchapparchitecture/definition/parser
2:https://time.cumbuca.com/parsers-n%C3%A3o-tenha-medo-deles-ee104cb27e05
3:https://johnidm.gitbooks.io/compiladores-para-humanos/content/part1/syntax-analysis.html
4:https://www.ic.unicamp.br/~celio/inf533/docs/markup.html

**Comment by Julio1099** [comment]
Gostei muito desses tutoriais:

1:https://youtu.be/xYQt8fyXSp0?si=Z1qJkt7FWgb1o3nK
2:https://youtu.be/CZcU40CcWf8?si=CyVs0P4PWrIKR-8Q
