### ISSUE TITLE
Prototipagem da interface do site no Figma

### ISSUE THREAD

**Issue by DaniloCTM** [unb-mds/2023-2-Squad04#27]
# Descrição 
Para que o usuário final tenha acesso aos dados, devemos criar uma plataforma online. O primeiro passo para a criação da plataforma é desenvolver o protótipo, para isso vamos utilizar o Figma.
# Objetivos 
- [x] Criar um protótipo no figma e compartilhar com o restante da equipe
- [x] Desenvolver um protótipo com uma interface amigável para o usuário
- [x] O protótipo deve atender os requisitos funcionais do projeto

**Comment by DaniloCTM** [comment]
Site para conseguir inspirações - https://dribbble.com

**Comment by patyhelenaa** [comment]
primeira versão do protótipo finalizada, esta disponível na documentação. :)
