### ISSUE TITLE
Conversão de PDF para formato (txt, csv)

### ISSUE THREAD

**Issue by DaniloCTM** [unb-mds/2023-2-Squad04#29]
# Descrição
Para o processamento do dado é necessário passar para um formato mais fácil de trabalhar, para que assim possamos utilizar python e suas bibliotecas para tratar os dados. Existem dois formatos que podem facilitar o processamento dos dados, txt e csv.

# Objetivos
- [x] Selecionar o melhor formato para o dado (txt, csv)
- [x] Criar um script para mudar o formato do arquivo
- [x] Verificar se nenhuma informação foi perdida no processo de conversão
- [x] Subir script para o github
- [x] Documentar o processo

**Comment by show-dawn** [comment]
O melhor formato para apresentação de dados é o CSV, pois ele permite uma estrutura de texto mais organizado com uma separação de valores superior. Além da compatibilidade para muitos aplicativos e flexibilidade muito boa do CSV.

**Comment by show-dawn** [comment]
Foi utilizado a biblioteca PyPDF2 (Sugerido pelo Danilo), uma biblioteca open-source capaz de dividir, mesclar, cortar e transformar páginas de arquivos PDF, além de poder extrair dados para formar um arquivo CSV.
link da documentação : https://pypdf2.readthedocs.io/en/3.0.0/
