### ISSUE TITLE
Extração e formatação do dado escolhido

### ISSUE THREAD

**Issue by Julio1099** [unb-mds/2023-2-Squad04#60]
# Descrição
Com os arquivos devidamente organizados e separados devemos extrair o dado escolhido (Licitações), e fazer a formatação do mesmo.
# Objetivos
- [x] Verificar se é melhor usar regex ou machine learning para extrair os dados
- [x] Realizar a extração do dado escolhido
- [x] Formatar o dado extraído
- [x] Documentar o processp
- [x] Adicionar os códigos no Github

**Comment by show-dawn** [comment]
é melhor usar o Regex, pois é muito mais simples, além de dispor de controle e precisão excelentes e uma velocidade rapida

**Comment by Julio1099** [comment]
A issue foi concluída com sucesso, entretanto, foi identificado que os arquivos CSV estavam incorretos.
